name: realworld-servant
version: '0.1.0.0'
category: Web
author: Louis Pilfold
maintainer: louis@lpil.uk
copyright: 2017 Louis Pilfold
license: BSD3
github: lpil/realworld-servant

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

dependencies:
  - base >=4.7 && <5
  - aeson
  - servant-server
  - here

library:
  source-dirs: src

executables:
  realworld-servant:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - realworld-servant
      - warp
      - wai

tests:
  realworld-servant-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - realworld-servant
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
